version: '3.8'

services:
  windows:
    image: dockur/windows # This is the correct image name.
    container_name: windows
    environment:
      - VERSION=11
      - USERNAME=Atul
      - PASSWORD=Game1234
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: '14G'
    restart: always
    stop_grace_period: 2m
