version: '3.8'

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      - VERSION=11
      - USERNAME=Atul
      - PASSWORD=game1234
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        reservations:
          cpus: '4'
          memory: '14G'
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=1sexnbULPxa5yDKR7xImFKqCg8o_335Laer65GytXuseDwNEH
    command: tcp windows:3389
    depends_on:
      - windows
    restart: always
